def main():
    startWorkSpace()
    for i in range(45):
        executeTask()
#___________________________________________________________________________________________________________________________________________________________________________________________________________________________
def startWorkSpace():
    # Open Chrome
    type(Key.WIN)
    wait(0.1)
    type("Google Chrome")
    type(Key.ENTER)
    wait(0.1)
    
    # Make Fullscreen
    keyDown(Key.WIN)
    type(Key.UP)
    keyUp(Key.WIN)
    wait(0.1)
    
    # Open new tab
    keyDown(Key.CTRL)
    type("t")
    keyUp(Key.CTRL)
    wait(0.1)
    
    # Navigate to the URL
    type("http://yourwebsite.com/wp-admin")
    type(Key.ENTER)
#___________________________________________________________________________________________________________________________________________________________________________________________________________________________
def uploadPDF():
    wait("PDFPoster.png", 60)
    click("PDFPoster.png")
    wait("AddNewPdf.png", 60)
    click("AddNewPdf.png")
    wait(Pattern("DobavqneNaZaglavie.png").similar(0.72), 60)
    wait(1)
    type(Key.PAGE_DOWN)
    
    wait("Upload.png", 60)
    click("Upload.png")
    wait("KachvaneNaFailove.png", 60)
    click("KachvaneNaFailove.png")
    wait("IzborNaFailove.png", 60)
    click("IzborNaFailove.png")
    
    wait(Pattern("toBeUploaded.png").similar(0.73), 60)
    click(Pattern("toBeUploaded.png").similar(0.73))
    wait(0.1)
    type(Key.TAB)
    wait(0.1)
    type(Key.DOWN)
    wait(0.1)
    keyDown(Key.CTRL)
    type("x")
    keyUp(Key.CTRL)
    wait(0.1)
    type(Key.UP)
    wait(0.1)
    type(Key.ENTER)
    wait(0.1)
    keyDown(Key.CTRL)
    type("v")
    keyUp(Key.CTRL)
    wait(0.1)
    type(Key.F2)
    wait(0.1)
    keyDown(Key.CTRL)
    type("c")
    keyUp(Key.CTRL)
    wait(0.1)
    type(Key.ENTER)
    wait(0.1)
    type(Key.ENTER)
    
    wait(3)
    click(Pattern("Opisanie.png").similar(0.78))
    keyDown(Key.CTRL)
    type("v")
    keyUp(Key.CTRL)
    wait("Izbor.png", 60)
    click("Izbor.png")
    wait(Pattern("AllowPrint.png").targetOffset(150,4), 60)
    click(Pattern("AllowPrint.png").targetOffset(150,4))
    click(Pattern("ShowFileNameOnTop.png").targetOffset(150,0))
    
    type(Key.PAGE_UP)
    wait(Pattern("DobavqneNaZaglavie.png").similar(0.72).targetOffset(0,12), 60)
    click(Pattern("DobavqneNaZaglavie.png").similar(0.72).targetOffset(0,12))
    keyDown(Key.CTRL)
    type("v")
    keyUp(Key.CTRL)
    click(Pattern("pdfId.png").exact())
    keyDown(Key.CTRL)
    type("c")
    keyUp(Key.CTRL)
    wait("save.png", 60)
    click("save.png")
    wait("redaktirane.png", 60)
#___________________________________________________________________________________________________________________________________________________________________________________________________________________________
def elementor():
    click("Stranici.png")
    wait("DoFnGBPP.png", 60)
    click("DoFnGBPP.png")
    wait("redaktiraneVElementor.png", 60)
    click("redaktiraneVElementor.png")
    
    wait("pdf.png", 60)
    click(Pattern("pdf.png").targetOffset(0,-350))
    type(Key.PAGE_DOWN)
    wait(0.1)
    wait("firstElement.png", 60)
    click("firstElement.png")
    wait(Pattern("1682506938927.png").exact(), 60)
    click(Pattern("1682506938927.png").exact().targetOffset(0,10))
    keyDown(Key.PAGE_DOWN)
    wait(1)
    keyUp(Key.PAGE_DOWN)
    wait("1682496378064.png", 60)
    click("1682496378064.png")
    wait("zaglavieNaRazdela.png", 60)
    click("zaglavieNaRazdela.png")
    keyDown(Key.CTRL)
    type("a")
    keyUp(Key.CTRL)
    wait(0.1)
    type("x")
    click(Pattern("tekstovRedaktor.png").similar(0.78))
    wait(Pattern("sudurjanie.png").targetOffset(0,55), 60)
    click(Pattern("sudurjanie.png").targetOffset(0,55))
    keyDown(Key.CTRL)
    type("a")
    type("v")
    keyUp(Key.CTRL)
    click("update.png")
    wait(5)
    click()
    type(Key.F6)
    type("http://dglib.escom.bg/wp-admin")
    type(Key.ENTER)
#___________________________________________________________________________________________________________________________________________________________________________________________________________________________
def executeTask():
    uploadPDF()
    elementor()
#___________________________________________________________________________________________________________________________________________________________________________________________________________________________
main()
